- name: delete the app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: delete the app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /app
    remote_src: yes

 