- name: disable the nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable the nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install the nodejs
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - nodejs
    - mysql

- name: install dependencies and libraries like pymysql
  ansible.builtin.pip:
    name:
      - pymysql
      - cryptography
    executable: pip3.9

- name: create a user
  ansible.builtin.user:
    name: expense

- name: run app-pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: install npm
  ansible.builtin.command: "npm install"
  args:
    chdir: /app

- name: copy the backend.service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: import the data into mysql
  community.mysql.mysql_db:
    login_host: "{{login_host}}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: import
    name: all
    target: /app/schema/backend.sql

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: start and enable backend service
  ansible.builtin.service:
    name: backend
    state: restarted
    enabled: yes
